name: Test

on:
  push:
  pull_request:

jobs:
  test-leiningen:
    name: Test Leiningen

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          lein: 2.9.8

      - name: Cache Leiningen dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: lein-${{ runner.os }}-${{ hashFiles('**/project.clj') }}
          restore-keys: lein-${{ runner.os }}-

      - name: Leiningen Install
        run: lein install

      - name: Version
        run: lein version

      - name: Leiningen Test
        uses: coactions/setup-xvfb@v1
        with:
          run: lein test

  test-cljs:
    name: Test ClojureScript

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache deps.edn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: cljs-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: cljs-${{ runner.os }}-

      # Java 17 generates class file version 61.0, which is what processing has
      # been compiled with.
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: latest
          bb: latest

      - name: Install Processing jars
        run: bb processing-install

      # AOT compile applet-listener and applet so CLJS compile can run
      - name: AOT Compile
        run: clojure -T:build aot

      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
          run: clojure -Mfig:cljs-test

  test-clj:
    name: Test Clojure

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache deps.edn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: clj-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: clj-${{ runner.os }}-

      # Java 17 generates class file version 61.0, which is what processing has
      # been compiled with.
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: latest
          bb: latest

      - name: Install Processing jars
        run: bb processing-install

      # AOT compile applet-listener and applet
      - name: AOT Compile
        run: clojure -T:build aot

      - name: Test
        uses: coactions/setup-xvfb@v1
        with:
          run: clojure -X:test

      
